[general]
caption_extension = '.caption'
shuffle_caption = false
# resolution has to be set, but I think it's disabled with bucket_no_upscale
resolution = 1024
# res bucketing
enable_bucket = true
bucket_no_upscale = true

[[datasets]]
batch_size = 4

  [[datasets.subsets]]
  # 4 images, rescaled to 4 sizes
  class_tokens = "raff person"
  image_dir = "garouste_data/webcam/obj_iman_light_colour_2.0"