[model]
pretrained_model_name_or_path = "/root/home/github/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors"
xformers = true
#noise_offset = 0.1
mixed_precision = "bf16"
full_bf16 = true
flip_aug = false
color_aug = false
name = ""
output_dir = ""

[schedule]
max_train_steps = 200
train_batch_size = 8

[optimizer]
optimizer_type = "adafactor"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False" ]
lr_scheduler = "constant_with_warmup"
lr_warmup_steps = 10
unet_lr = 1e-3
scale_weight_norms = 2

[network]
network_module = "networks.lora"
network_train_unet_only = true
network_dim = 4
network_alpha = 3

[cache]
gradient_checkpointing = true
cache_latents = true
cache_text_encoder_outputs = true