[model]
pretrained_model_name_or_path = "/root/home/github/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors"
xformers = true
noise_offset = 0.1
flip_aug = true
color_aug = false

[schedule]
gradient_checkpointing = true
max_train_epochs = 5
mixed_precision = "bf16"
full_bf16 = true
scale_weight_norms = 2.0

[optimizer]
optimizer_type = "adafactor"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False" ]
lr_scheduler = "constant_with_warmup"
lr_warmup_steps = 20
unet_lr = 1e-3

[network]
network_module = "networks.lora"
network_train_unet_only = true
network_dim = 2
network_alpha = 3

[cache]
cache_latents = false
cache_text_encoder_outputs = true

